################################################################################
#                                                                              #
# db    db  .8888.  dP     888888b 8888ba   .8888.     d8b   db 888888b d8888P #
# 88    88 d8'  `8b 88     88      88  `8b d8'  `8b    88V8  88 88        88   #
# Y8    8P 88    88 88    a88aaa   88aa8P' 88    88    88 V8 88 88aaa     88   #
# `8b  d8' 88    88 88     88      88  `8b 88    88    88  V888 88        88   #
#  `8bd8'  Y8.  .8P 88     88      88  .88 Y8.  .8P dP 88   V88 88        88   #
#    YP     `888P'  88888P 888888P 888888'  `888P'  88 VP    8P 888888P   dP   #
#                                                                              #
################################################################################
#
# ExpressJS for volebo.net
#
# Copyright (C) 2016-2018 Volebo <dev@volebo.net>
# Copyright (C) 2016-2018 Maksim Koryukov <maxkoryukov@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

sudo: false

language: node_js

node_js:
  - 6
  - 8

# env:
#  global:
#    - NODE_ENV=dev

#matrix:
  # include:
  #   - node_js: 4
  #     env: WITHTESTS=1
  # allow_failures:
  #   - node_js: 4

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

#before_script:
#  - npm install -g npm
#  - npm install -g gulp

install:
  - npm install
  - npm install -g codecov
  - npm install -g bithound

script:
# - gulp build
  - npm run lint
  - npm test
  - npm run coverage
  - bithound check git@github.com:$TRAVIS_REPO_SLUG.git || /bin/true

after_success:
  - codecov

deploy:
  provider: npm
  api_key:
    secure: "y9JYrR/6PVzgJZjVs7ZPmTW7LR7yYUXmFIMigzuzEJ6IzH9hKUC/QbXagyCR2CM6yVu0xU/zsrhQ0RYALxeHcz1JELZheKysRQey+fxjBWD+b4hzcJRpVVKgVftW/3zf93njTVt3Kkksfx9k1AxQ/Iw0a8o9zxku6nQu+vs5udrjDvsCHGRwLiyVcgJGF0l9vMZXkTIkIxWr7rMRNoHSiFEdrpbv9bSDFqoJ/Fwycg/V+da1GVEuyaYKsd20OicfMdEI3wJsc+IAYbTANQpX0QEV5xtcyJ+njYlyB5FEacMXhKFrhpUiznh5Ajnz0XWTVCr1t3zgsgaTtbyAaj6w16EXOmwLJ2se08sRKX/Kxi6VWNVvQ05AWvsENM5Ly0HLzZsukGN1WweS1Qt47yZJ9UbF6WkF38rfo8DJpNc3zve7KQ7gZD7JYq0GjZeFo5IoZqqg6evUjEvFKkX7Ipgnhu9ZHQpeYoA0TauYIMHkzMp+t/y2cWEJAJqJ1LFYIUwODaepw5vWQMQguBqrOUZUdw5/UI9WRgtBlCBaoY0RZT29TjvKIoDrqFkwIqIQhYy1NPDavyvh/JVVKYvbbTBdL/AEV3voDopFflhDZiWnAIa7XSJHrdHx3v+7LZbVvHeUWHdoiXuFbFLwkSga6x32BVSwZN3LNOMXaIQOUeRtD3g="
  email:
    secure: "IzQtOIghymGPZk2l2fqQBZmsb/WQJKNGDEl7p/AagczQWP9OSUvjV8HnUE1tGBI8wBl6gf2spF4MQSg7EEXoloj8/i8einstYF92rkYT11ukrAbbSvghUhobcZnW4tPfGTTGnWeHpLndEoITsdqGIDSVohXVyuCSICZl2THWFfmAEZwwjq62q9OO1NjvhX66uTwcdx6KK02kDkvoqCgkDE2LG4QW43t+SCdHAc+LqnNR23WePKOIdd2C/9zXQIEFw6NRJlgKD6aNhPgu7cUHeBWDAPHVyfcU6JY6dZsXOuxiaByT6mEESXJPn6knghs6VTRkTQoGtLsog4nukWVIuhEGIGLAjR8W8gEagRuc4nj3dLCkm7xNirEmf9yASxIMAU/7a7NMJCz/VT3BDLRZx8SwyC4m8H/XMmvQmapDi8cKuH7eNKaI934ypaN+DHpy5JjcGFLW0U02ByhEMTGhPE9th6vR4JbSp3vvxbe7iijqimCBAJFBVh2U/cSjl0YjvMg32NgjSi7IG/NKR+ReAnPP3soFTiM54Ym+lUvogWfTbdn5NpRhKD0pjpDtPGWbQ6ZpUNKMJNLAI6NPRp328YAdp8hd4luaNEY1TsAeznFa20nimyIEqvhmxzlHVlSfKq4wwGiC4d1cG5z//dzU53di+4Hp9KUe5CzZTQdPYd8="
  on:
    tags: true
    node_js: 8
    repo: volebo/express

after_deploy:
  # Send notification to Slack:
  - curl -sL https://raw.githubusercontent.com/volebo/dev/master/scripts/im/slack-publish.sh | bash -s -
